### PR TITLE
Add rv32a

### PR DESCRIPTION
**Pull request by youzi27**
Hi @flaviens ,

After testing, the rv32a instructions can be tested normally.

Thank you.

### CODE REVIEW

**Comment by flaviens** [comment]
Hi @youzi27 , thank you for opening this pull request.
I'd have a couple of questions both to help the review and to help future users.
a) Can you please tell which portion of rv32a is intended to be covered by this PR and which not?
b) Can you explain the design decisions that you had to do, and potential consequences?
c) I still see a todo comment in the code. What is its status?
Thanks!
Flavien

**Comment by youzi27** [comment]
Hi @flaviens ,

Thank you for your reply.

Regarding question a), This PR covers the tests in rv32a for all legal operations except the LR instruction, and does not cover: testing of the LR instruction and other illegal memory access tests (because the address is forced to be aligned and accessible).

Regarding question b), my approach for rv32a is: to forcibly insert a `fence` instruction for memory **synchronization** in all rv32a instructions, of course, it is necessary to **check** whether this basic block can still insert instructions during the insertion process. The reason why the `LR` instruction is not tested is to avoid some exceptions that could cause the entire framework to timeout.

Regarding question c): 1. Efforts still need to be made to test the `LR` instruction; 2. To facilitate debugging, this PR outputs the values of all integer registers when there is a mismatch for debugging, but I still have not done so for the floating-point registers.

If you have any other questions, feel free to ask, and I will reply tomorrow (it's too late here😊).

Thank you.

**Comment by flaviens** [comment]
Hi @youzi27,

Thank you for your prompt response!
I'll carefully review the PR in a few weeks (sched unusually busy sorry).

In the meanwhile, do you plan to implement the whole (c) into the same PR?

While merging is not at all conditioned to that, by curiosity did you manage to find any new bugs with this new feature?

Thanks & good night!
Flavien

**Comment by youzi27** [comment]
Thank you for your reply!

No problem, I just provided a way to implement the 'a' extension in Cascade, which may not be the best but is functional. Besides that, I agree with your suggestion to split this PR into two for future submissions. 

Regarding whether any new bugs were discovered, I only tested the 'a' extension with Boom and Rocket. Rocket has had no issues, but Boom showed some mismatches and timeouts. However, since I am currently focusing on perfecting my framework, I have not had the time to analyze these issues in depth. Of course, I will analyze it when I have time later.

Thank you😊!

**Comment by flaviens** [comment]
Hi @youzi27, Thank you for your response!
When you have time, I suggest looking closer to these phenomena on BOOM to see whether these are bugs or things to be improved in the PR.

**Comment by youzi27** [comment]
Thank you very much for your response! 

If there are no issues with the analysis later, I'll split this PR. So feel free to close this one anytime.

Thank you!

**Pull request closed without merging**
